dns_port: 53
listen_address: "127.0.0.1,192.168.10.100"
local_domain: "dev.local"
cache_size: 1000
local_domain_list:
  - address=/k8s-master.{{ local_domain }}/192.168.10.27
  - address=/k8s-worker1.{{ local_domain }}/192.168.10.26
  - address=/k8s-worker2.{{ local_domain }}/192.168.10.25
  - address=/.{{ local_domain }}/192.168.10.24

nameservers_list:
  - 8.8.8.8
  - 192.168.10.254