---
- name: Install pre requirements packages
  apt:
    name:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    update_cache: yes

- name: Add Kubernetes and Docker repo keys using apt-key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ k8s_version }}/deb/ /"
    state: present
    filename: 'kubernetes'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: 'docker'

- name: Install Kubernetes and Docker packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - containerd.io
    state: present
    update_cache: yes

- name: Configure containerd
  lineinfile:
    path: "{{ item.path }}"
    line: "{{ item.line }}"
    create: yes
  loop:
    - {path: "/etc/modules-load.d/containerd.conf", line: "overlay"}
    - {path: "/etc/modules-load.d/containerd.conf", line: "br_netfilter"}

- name: Add kernel module
  shell: |
    modprobe overlay
    modprobe br_netfilter