---
- name: Set k8s sysctl config
  lineinfile:
    path: "/etc/sysctl.d/k8s.conf"
    line: "{{ item.line }}"
    create: yes
  loop:
   - {line: "net.bridge.bridge-nf-call-iptables  = 1"}
   - {line: "net.ipv4.ip_forward = 1"}
   - {line: "net.bridge.bridge-nf-call-ip6tables = 1"}
- name: Apply sysctl config
  shell: sysctl --system
- name: Fix kubelet config
  template:
    src: "kubelet.j2"
    dest: "/etc/default/kubelet"
- name: Copy containerd template
  template:
    src: "config.toml.j2"
    dest: "/etc/containerd/config.toml"
- name: Copy crictl template config
  template:
    src: "crictl.yaml.j2"
    dest: /etc/crictl.yaml
- name: Run container runtime
  systemd:
    name: "{{ container_runtime }}"
    state: restarted
    enabled: yes
- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes