---
- name: Disable swap
  shell: swapoff -a
- name: Disable swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - {regexp: "^/swapfile", line: "# /swapfile"}
    - {regexp: "^/swap.img", line: "# /swap.img"}