kubernetes:
  children:
    init-master:
      hosts:
        k8s-master:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: vagrant
          ansible_ssh_private_key_file: /srv/vagrant/k8s/.vagrant/machines/k8s-master/virtualbox/private_key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  
    master:
      hosts: {}  
    node:
      hosts:
        k8s-worker1:
          ansible_host: 127.0.0.1
          ansible_port: 2223
          ansible_user: vagrant
          ansible_ssh_private_key_file: /srv/vagrant/k8s/.vagrant/machines/k8s-worker1/virtualbox/private_key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  
        k8s-worker2:
          ansible_host: 127.0.0.1
          ansible_port: 2224
          ansible_user: vagrant
          ansible_ssh_private_key_file: /srv/vagrant/k8s/.vagrant/machines/k8s-worker2/virtualbox/private_key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  
    ingress:
      hosts:
        k8s-ingress1:
          ansible_host: 127.0.0.1
          ansible_port: 2226
          ansible_user: vagrant
          ansible_ssh_private_key_file: /srv/vagrant/k8s/.vagrant/machines/k8s-ingress1/virtualbox/private_key
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 
